ALTER TABLE users
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'user',
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
